# Example YAML for the bare minimum of required elements
info:
  version: "1.0.0"
  title: petstore
parameters:
  productId: 
       name: productId
       in: path
       type: string
       required: true
paths:
  /users:
    get:
      parameters:
        -
          $ref: '#/parameters/productId'
      responses:
        "200":
          description:  Describe the 200 response in more detail