openapi: 3.0.0
info:
  title: Test API
  version: '1.0'
  description: Users
  contact:
    email: test@testemail.com
    name: Sarah
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - type: string
        name: userId
        in: path
        required: true
    get:
      summary: getUser
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      description: Get users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                userId:
                  type: number
      operationId: 12345
    post:
      summary: ''
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
      description: Add users
components:
  schemas: {}
